### ISSUE TITLE
Help with HTML GameboyEMU Setup

### ISSUE THREAD

**Issue by ChefFloyardee** [aracitdev/GameBoyEmu#1]
Hi there!

I currently host a ROM Hack on my website using an embedded flash emulator, but since Chrome is going to discontinue flash soon I am looking for a Java/other type of embedded emulator to replace it with.

I found your GameBoyEMU, and I was wondering if this would work for me. If so, could you help me set it up?

Thanks and let me know :D

**Comment by aracitdev** [comment]
Unfortunately this would be very very difficult to do due to the nature of how this emulator is written. This emulator using c++ (which is a compiled language that needs to be run directly on the machine). Short of either hosting a server that runs the emulator and forwards inputs and screens or running it on a computer it is impossible. It is possible, however, if you find/make one that runs entirely in browser (using something like javascript).
I can give you some further pointers should you need them.
